### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by thecr8tr**
Have a look at the changed files before you merge them with your branch.

Cleaned code for block3bx.scad and block5.scad
Added a metric screw dimemsion file
Added balljoint adapters to basic block

### CODE REVIEW

**Comment by pkTux** [comment]
I like it all so far.. The code cleanup looks amazing, and i can understand it better.

On block 5 we want/need the 9mm hole to attache pulley's/bearings for the other end of the fishing line  loop.
Can you put that back? i will approve this as is for now.

**Comment by pkTux** [comment]
how do  i merge this? i am git-handicaped

**Comment by thecr8tr** [comment]
wait on merging for now...I started another branch locally and I'm building
each item using includes and cleaning code.  Then we can see what we like
and dump the rest.  The file I got did not have the hole for the
pulley/bearings.  Is it just centered?

Thank You,
Kristy Knight
Innovative Bookkeepers
386-843-0698

**Comment by pkTux** [comment]
yep, 9mm centered iirc. do you see  a file called Mblock 5?
hm.. my.. machine some how shows all your changes, live, to my folder, and
a backup i made before i opened Git today.
 well . i thinik.. i am new to GIt.
 but keep up the work. dont mind me.

**Comment by thecr8tr** [comment]
No problem. I must have pulled before you updated the files.

Thank You,
Kristy Knight
Innovative Bookkeepers
386-843-0698

**Pull request closed without merging**
